ALTER TABLE users DROP q1;
ALTER TABLE users DROP q2;
ALTER TABLE users DROP q3;
ALTER TABLE users DROP q4;
ALTER TABLE users DROP q5;
ALTER TABLE users DROP q6;
ALTER TABLE users DROP q7;
ALTER TABLE users DROP fullName;